base_dir: "data"

crawl:
  semianalysis:
    output: "${base_dir}/semianalysis.jsonl"

  theinformation:
    output: "${base_dir}/theinformation.jsonl"

  rss:
    feeds_file: "feeds.txt"
    output_dir: "${base_dir}/rss"

process:
  articles:
    semianalysis:
      input: "${crawl.semianalysis.output}"
      output: "${base_dir}/processed_semianalysis.jsonl"

    theinformation:
      input: "${crawl.theinformation.output}"
      output: "${base_dir}/processed_theinformation.jsonl"

  rss:
    feeds_file: "${crawl.rss.feeds_file}"
    input_dir: "${crawl.rss.output_dir}"
    output_dir: "${base_dir}/rss/processed"

  kg:
    raw:
      input:
        - "${process.articles.semianalysis.output}"
        - "${process.articles.theinformation.output}"
      output: "${base_dir}/knowledge_graph"

    refine:
      input: "${process.kg.raw.output}"
      output: "${base_dir}/refined_knowledge_graph"

chat:
  start:
    raw_articles: "${base_dir}/chat/raw_articles.jsonl"
    processed_articles: "${base_dir}/chat/processed_articles.jsonl"

api:
  financialdatasets:
    facts:
      input: "${process.kg.raw.output}/tickers.parquet"
      output: "${base_dir}/financialdatasets/facts.json"
    metrics:
      input: "${process.kg.raw.output}/tickers.parquet"
      output: "${base_dir}/financialdatasets/metrics.json"
    price:
      input: "${process.kg.raw.output}/tickers.parquet"
      output: "${base_dir}/financialdatasets/price.json"
    tickers:
      output: "${base_dir}/financialdatasets/tickers.json"

  sec:
    download:
      tickers_file: "${process.kg.raw.output}/tickers.parquet"
      output_dir: "${base_dir}/sec/tickers"
      xbrl_files: "${base_dir}/sec/xbrl_files"
      html_filings: "${base_dir}/sec/html_filings"

  dump:
    companies:
      input: "${process.kg.refine.output}/companies.parquet"
