base_dir: "data"

crawl:
  ignore:
    - "wsj.com"
    - "github.com"
    - "stocktwits.com"

  semianalysis:
    output: "${base_dir}/articles/semianalysis.jsonl"

  theinformation:
    output: "${base_dir}/articles/theinformation.jsonl"

  rss:
    feeds:
      wsj-tech: "https://feeds.content.dowjones.io/public/rss/RSSWSJD"
      wsj-markets: "https://feeds.content.dowjones.io/public/rss/RSSMarketsMain"
      techcrunch: "https://techcrunch.com/feed/"
      wired: "https://www.wired.com/feed/tag/ai/latest/rss"
      nvidia-blog: "https://developer.nvidia.com/blog/rss"
    output_dir: "${base_dir}/rss"

  reddit:
    input: "${base_dir}/reddit/reddit_posts.jsonl"
    output: "${base_dir}/reddit/processed_reddit_posts.jsonl"

process:
  articles:
    semianalysis:
      input: "${crawl.semianalysis.output}"
      output: "${base_dir}/articles/processed_semianalysis.jsonl"

    theinformation:
      input: "${crawl.theinformation.output}"
      output: "${base_dir}/articles/processed_theinformation.jsonl"

  rss:
    input_dir: "${crawl.rss.output_dir}"
    output_dir: "${base_dir}/rss/processed"

  kg:
    raw:
      input:
        - "${process.articles.semianalysis.output}"
        - "${process.articles.theinformation.output}"
        - "${crawl.rss.output_dir}/*.jsonl"
        - "${chat.start.processed_articles}"
        - "${crawl.reddit.input}"
      output: "${base_dir}/knowledge_graph"

    refine:
      input: "${process.kg.raw.output}"
      output: "${base_dir}/refined_knowledge_graph"

chat:
  start:
    raw_articles: "${base_dir}/chat/raw_articles.jsonl"
    processed_articles: "${base_dir}/chat/processed_articles.jsonl"

api:
  financialdatasets:
    facts:
      input: "${process.kg.raw.output}/tickers.parquet"
      output: "${base_dir}/financialdatasets/facts.json"
    metrics:
      input: "${process.kg.raw.output}/tickers.parquet"
      output: "${base_dir}/financialdatasets/metrics.json"
    price:
      input: "${process.kg.raw.output}/tickers.parquet"
      output: "${base_dir}/financialdatasets/price.json"
    tickers:
      output: "${base_dir}/financialdatasets/tickers.json"

  sec:
    download:
      tickers_file: "${process.kg.raw.output}/tickers.parquet"
      output_dir: "${base_dir}/sec/tickers"
      xbrl_files: "${base_dir}/sec/xbrl_files"
      html_filings: "${base_dir}/sec/html_filings"

dump:
  companies:
    input: "${process.kg.refine.output}/companies.parquet"
  products:
    input: "${process.kg.refine.output}/products.parquet"
  returns:
    input: "${api.financialdatasets.price.output}"
  tickers:
    url: "https://www.sec.gov/files/company_tickers.json"
    cache: "data/sec/company_tickers.json"
