apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: s3storage
spec:
  type: bindings.aws.s3
  version: v1
  metadata:
    - name: bucket
      value: abzu-cache
    - name: accessKey
      secretKeyRef:
        name: s3-access-key
        key: s3-access-key
    - name: secretKey
      secretKeyRef:
        name: s3-secret-key
        key: s3-secret-key
    - name: endpoint
      secretKeyRef:
        name: s3-endpoint
        key: s3-endpoint
    - name: forcePathStyle
      value: "true"
    - name: region
      value: us-east-1
  auth:
    secretStore: local-secret-store 