apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
spec:
  type: state.redis
  version: v1
  metadata:
    - name: redisHost
      value: redis:6379
    - name: redisPassword
      value: abzu_redis_pass
    - name: actorStateStore
      value: "true"
    - name: redisDB
      value: 0
    - name: maxRetries
      value: 5
    - name: failover
      value: false
  auth:
    secretStore: local-secret-store 